In [16]:
import osmnx as ox
import geopandas as gpd
import os
from pathlib import Path

In [4]:
waianae_gdf= ox.geocode_to_gdf( "Waianae, Hawaii")

In [13]:
#https://osmnx.readthedocs.io/en/stable/user-reference.html
geometry = waianae_gdf.geometry.iloc[0]

waianae_drive_graph=ox.graph_from_polygon(

    geometry,
    network_type="drive"

)    
gdf_drive_edges=ox.graph_to_gdfs(waianae_drive_graph, nodes=False
)
gdf_drive_edges.to_file("waianae_drive.geojson",driver="GeoJSON")
gdf_drive_edges.head()

                                           osmid      highway lanes  \
u         v          key
110501070 2405706391 0                  12197068  residential     2
110502972 4946488885 0                  12216631  residential   NaN
110526827 2405706278 0                 685984869     tertiary   NaN
          634521063  0                  12200814     tertiary     2
          110611890  0    [1176085682, 12221789]     tertiary   NaN

                                         name  oneway reversed      length  \
u         v          key
110501070 2405706391 0        Kilouhane Place   False     True   32.635771
110502972 4946488885 0       Ala Walua Street   False     True  224.955732
110526827 2405706278 0    Old Government Road   False    False   11.167211
          634521063  0    Old Government Road   False     True  328.644912
          110611890  0        Plantation Road   False     True   98.607832

                                                                   geometry  \
u         v          key
110501070 2405706391 0    LINESTRING (-158.18181 21.44863, -158.1821 21....
110502972 4946488885 0    LINESTRING (-158.19405 21.4546, -158.19453 21....
110526827 2405706278 0    LINESTRING (-158.18788 21.44598, -158.18791 21...
          634521063  0    LINESTRING (-158.18788 21.44598, -158.18792 21...
          110611890  0    LINESTRING (-158.18788 21.44598, -158.18778 21...

                         maxspeed  ref bridge
u         v          key
110501070 2405706391 0        NaN  NaN    NaN
110502972 4946488885 0        NaN  NaN    NaN
110526827 2405706278 0        NaN  NaN    NaN
          634521063  0        NaN  NaN    NaN
          110611890  0        NaN  NaN    NaN

In [14]:
waianae_walk_graph=ox.graph_from_polygon(

    geometry,
    network_type="walk"

)    
gdf_walk_edges=ox.graph_to_gdfs(waianae_walk_graph, nodes=False
)
gdf_walk_edges.to_file("waianae_walk.geojson",driver="GeoJSON")
gdf_walk_edges.head()

                             osmid      highway lanes              name  \
u         v          key
110501070 2405706391 0    12197068  residential     2   Kilouhane Place
110502925 110502927  0    12197537      service   NaN               NaN
          110502972  0    12216631  residential   NaN  Ala Walua Street
          110535060  0    12216631  residential   NaN  Ala Walua Street
          634521374  0    12197537      service   NaN               NaN

                          oneway reversed      length  \
u         v          key
110501070 2405706391 0     False     True   32.635771
110502925 110502927  0     False    False  105.861599
          110502972  0     False    False   81.074711
          110535060  0     False     True   77.032922
          634521374  0     False     True  146.587562

                                                                   geometry  \
u         v          key
110501070 2405706391 0    LINESTRING (-158.18181 21.44863, -158.1821 21....
110502925 110502927  0    LINESTRING (-158.19453 21.45403, -158.19373 21...
          110502972  0    LINESTRING (-158.19453 21.45403, -158.19405 21...
          110535060  0    LINESTRING (-158.19453 21.45403, -158.195 21.4...
          634521374  0    LINESTRING (-158.19453 21.45403, -158.1948 21....

                         service maxspeed  ref bridge access
u         v          key
110501070 2405706391 0       NaN      NaN  NaN    NaN    NaN
110502925 110502927  0       NaN      NaN  NaN    NaN    NaN
          110502972  0       NaN      NaN  NaN    NaN    NaN
          110535060  0       NaN      NaN  NaN    NaN    NaN
          634521374  0       NaN      NaN  NaN    NaN    NaN

In [21]:
#https://docs.python.org/3/library/pathlib.html
data_folder = Path("data/raw")
data_folder.mkdir(parents=True, exist_ok=True)

path_drive = data_folder / "waianae_roads_drive.geojson"
path_walk = data_folder / "waianae_roads_walk.geojson"

gdf_drive_edges.to_file(path_drive, driver="GeoJSON")
gdf_walk_edges.to_file(path_walk, driver="GeoJSON")

In [23]:
len(gdf_walk_edges)

1394

In [24]:
len(gdf_drive_edges)

488